spring:
  application:
    name: oauth2-jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2_test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: test123
logging:
  level:
    org.springframework.security: debug